name: build

on:
  push:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    
    - name: Build war file
      run: mvn --no-transfer-progress package --file pom.xml
