/********************* ROLES **********************/

CREATE ROLE RDB$ADMIN;
CREATE ROLE R_WEB;
/********************* UDFS ***********************/

/****************** GENERATORS ********************/

CREATE GENERATOR GE_ARTICLE;
CREATE GENERATOR GE_ARTICLE_ATTACHMENT;
CREATE GENERATOR GE_ARTICLE_COMMENT;
CREATE GENERATOR GE_BUILDING;
CREATE GENERATOR GE_BUILDING_UNIT;
CREATE GENERATOR GE_COMPANY;
CREATE GENERATOR GE_INQUIRY;
CREATE GENERATOR GE_INQUIRY_OPTION;
CREATE GENERATOR GE_INQUIRY_VOTING_LOG;
CREATE GENERATOR GE_LOG;
CREATE GENERATOR GE_LOG_ROBOTS;
CREATE GENERATOR GE_MENU_TREE;
CREATE GENERATOR GE_MESSAGE_QUEUE;
CREATE GENERATOR GE_MINI_NEWS;
CREATE GENERATOR GE_ROLE;
CREATE GENERATOR GE_USER;
/******************** DOMAINS *********************/

/******************* PROCEDURES ******************/

SET TERM ^ ;
CREATE PROCEDURE SP_CREATE_COMPANY (
    NAME Varchar(50) )
RETURNS (
    COMPANY_ID Integer )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE SP_DROP_COMPANY (
    ID Integer )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE SP_DROP_USER (
    USER_ID Integer )
AS
BEGIN SUSPEND; END^
SET TERM ; ^

/******************** TABLES **********************/

CREATE TABLE APPLICATION_SETUP
(
  ID Varchar(50) NOT NULL,
  COMPANY_ID Integer NOT NULL,
  "VALUE" Varchar(1000),
  CONSTRAINT APPLICATION_SETUP_PK PRIMARY KEY (ID,COMPANY_ID)
);
CREATE TABLE ARTICLE
(
  ID Integer NOT NULL,
  COMPANY_ID Integer,
  MENU_NODE_ID Integer,
  LANGUAGE_ID Integer,
  HEADER Varchar(50),
  DESCRIPTION Blob sub_type 1,
  BODY Blob sub_type 1,
  CREATED_BY_USER_ID Integer,
  CREATION_DATE Timestamp,
  PUBLISHED Smallint,
  COMMENTS_ALLOWED Smallint,
  CONSTRAINT ARTICLE_PK PRIMARY KEY (ID)
);
CREATE TABLE ARTICLE_ATTACHMENT
(
  ID Integer NOT NULL,
  ARTICLE_ID Integer,
  USER_ID Integer,
  UPLOAD_TIME Timestamp,
  CONTENT_TYPE Varchar(250),
  FILENAME Varchar(250),
  DATA Blob sub_type 0,
  CONSTRAINT ARTICLE_ATTACHMENT_PK PRIMARY KEY (ID)
);
CREATE TABLE ARTICLE_COMMENT
(
  ID Integer NOT NULL,
  ARTICLE_ID Integer NOT NULL,
  USER_ID Integer NOT NULL,
  INSERTION_TIME Timestamp,
  BODY Blob sub_type 1,
  CONSTRAINT ARTICLE_COMMENT_PK PRIMARY KEY (ID)
);
CREATE TABLE ARTICLE_INQUIRY
(
  ID Integer NOT NULL,
  ARTICLE_ID Integer NOT NULL,
  DESCRIPTION Blob sub_type 1,
  VOTING_START Timestamp,
  VOTING_END Timestamp,
  CONSTRAINT ARTICLE_INQUIRY_PK PRIMARY KEY (ID)
);
CREATE TABLE ARTICLE_INQUIRY_OPTION
(
  ID Integer NOT NULL,
  INQUIRY_ID Integer,
  DESCRIPTION Varchar(250),
  CONSTRAINT ARTICLE_INQUIRY_OPTION_PK PRIMARY KEY (ID)
);
CREATE TABLE ARTICLE_INQUIRY_VOTING_LOG
(
  ID Integer NOT NULL,
  INQUIRY_OPTION_ID Integer NOT NULL,
  USER_ID Integer NOT NULL,
  VOTING_TIME Timestamp,
  CONSTRAINT ARTICLE_INQUIRY_VOTING_LOG_PK PRIMARY KEY (ID)
);
CREATE TABLE ARTICLE_IS_VISIBLE_TO_ROLE
(
  ARTICLE_ID Integer NOT NULL,
  ROLE_ID Integer NOT NULL,
  CONSTRAINT ARTICLE_IS_VISIBLE_TO_ROLE_PK PRIMARY KEY (ARTICLE_ID,ROLE_ID)
);
CREATE TABLE BUILDING
(
  ID Integer NOT NULL,
  COMPANY_ID Integer,
  ADDRESS Varchar(50),
  CITY Varchar(50),
  POST_CODE Varchar(10),
  REGISTRATION_ID Varchar(50),
  CONSTRAINT BUILDING_PK PRIMARY KEY (ID)
);
CREATE TABLE BUILDING_UNIT
(
  ID Integer NOT NULL,
  BUILDING_ID Integer,
  BUILDING_UNIT_TYPE_ID Integer,
  REGISTRATION_ID Varchar(50),
  DESCRIPTION Varchar(50),
  NUMERATOR Integer,
  DENOMINATOR Integer,
  CONSTRAINT BUILDING_UNIT_PK PRIMARY KEY (ID)
);
CREATE TABLE BUILDING_UNIT_TYPE
(
  ID Integer NOT NULL,
  DESCRIPTION Varchar(50),
  CONSTRAINT BUILDING_UNIT_TYPE_PK PRIMARY KEY (ID)
);
CREATE TABLE COMPANY
(
  ID Integer NOT NULL,
  NAME Varchar(50),
  ADDRESS Varchar(50),
  CITY Varchar(50),
  POST_CODE Varchar(10),
  PHONE Varchar(30),
  FAX Varchar(30),
  E_MAIL Varchar(30),
  REGISTRATION_NO Varchar(20),
  VAT_REGISTRATION_NO Varchar(20),
  DATABASE_CREATION_DATE Date,
  INTERNET_DOMAIN Varchar(50),
  PICTURE_CONTENT_TYPE Varchar(250),
  PICTURE_FILENAME Varchar(250),
  PICTURE_DATA Blob sub_type 0,
  CONSTRAINT COMPANY_PK PRIMARY KEY (ID)
);
CREATE TABLE INQUIRY
(
  ID Integer NOT NULL,
  COMPANY_ID Integer NOT NULL,
  USER_ID Integer NOT NULL,
  DESCRIPTION Blob sub_type 1,
  STARTING_DATE Timestamp,
  ENDING_DATE Timestamp,
  ENABLED Integer,
  CONSTRAINT INQUIRY_PK PRIMARY KEY (ID)
);
CREATE TABLE INQUIRY_OPTION
(
  ID Integer NOT NULL,
  INQUIRY_ID Integer,
  DESCRIPTION Varchar(250),
  CONSTRAINT INQUIRY_OPTION_PK PRIMARY KEY (ID)
);
CREATE TABLE INQUIRY_VOTING_LOG
(
  ID Integer NOT NULL,
  INQUIRY_OPTION_ID Integer NOT NULL,
  USER_ID Integer NOT NULL,
  VOTING_TIME Timestamp,
  CONSTRAINT INQUIRY_VOTING_LOG_PK PRIMARY KEY (ID)
);
CREATE TABLE LANGUAGE
(
  ID Integer NOT NULL,
  DESCRIPTION Varchar(50),
  CONSTRAINT LANGUAGE_PK PRIMARY KEY (ID)
);
CREATE TABLE LANGUAGE_DICTIONARY
(
  ID Varchar(50) NOT NULL,
  LANGUAGE_ID Integer NOT NULL,
  TEXT Blob sub_type 1,
  CONSTRAINT LANGUAGE_DICTIONARY_PK PRIMARY KEY (ID,LANGUAGE_ID)
);
CREATE TABLE LOG
(
  ID Integer NOT NULL,
  "TIME" Timestamp,
  USER_ID Integer,
  OPERATION_ID Integer,
  ARTICLE_ID Integer,
  REMOTE_IP Varchar(16),
  USER_AGENT Varchar(150),
  CONSTRAINT LOG_PK PRIMARY KEY (ID)
);
CREATE TABLE LOG_OPERATION
(
  ID Integer NOT NULL,
  DESCRIPTION Varchar(50),
  CONSTRAINT LOG_OPERATION_PK PRIMARY KEY (ID)
);
CREATE TABLE LOG_ROBOTS
(
  ID Integer NOT NULL,
  USER_AGENT Varchar(150),
  CONSTRAINT LOG_ROBOTS_PK PRIMARY KEY (ID)
);
CREATE TABLE MENU_TREE
(
  ID Integer NOT NULL,
  COMPANY_ID Integer,
  PARENT_ID Integer,
  DESCRIPTION Varchar(50),
  CONSTRAINT MENU_TREE_PK PRIMARY KEY (ID)
);
CREATE TABLE MESSAGE_QUEUE
(
  ID Integer NOT NULL,
  MESSAGE_TYPE_ID Integer NOT NULL,
  RECIPIENT Varchar(50),
  SUBJECT Varchar(100),
  BODY Blob sub_type 1,
  CREATION_TIME Timestamp,
  SENDING_TIME Timestamp,
  STATUS Smallint,
  COMPANY_ID Integer NOT NULL,
  CONSTRAINT MESSAGE_QUEUE_PK PRIMARY KEY (ID)
);
CREATE TABLE MESSAGE_TYPE
(
  ID Integer NOT NULL,
  DESCRIPTION Varchar(50),
  CONSTRAINT MESSAGE_TYPE_PK PRIMARY KEY (ID)
);
CREATE TABLE MINI_NEWS
(
  ID Integer NOT NULL,
  COMPANY_ID Integer,
  LANGUAGE_ID Integer,
  NEWS_TIME Timestamp,
  CREATED_BY_USER_ID Integer,
  PUBLISHED Smallint,
  BODY Blob sub_type 1,
  CONSTRAINT MINI_NEWS_PK PRIMARY KEY (ID)
);
CREATE TABLE PERMISSION
(
  ID Integer NOT NULL,
  DESCRIPTION Varchar(50),
  CONSTRAINT PERMISSION_PK PRIMARY KEY (ID)
);
CREATE TABLE "ROLE"
(
  ID Integer NOT NULL,
  COMPANY_ID Integer,
  DESCRIPTION Varchar(50),
  CONSTRAINT ROLE_PK PRIMARY KEY (ID)
);
CREATE TABLE ROLE_HAS_PERMISSION
(
  ROLE_ID Integer NOT NULL,
  PERMISSION_ID Integer NOT NULL,
  CONSTRAINT ROLE_HAS_PERMISSION_PK PRIMARY KEY (ROLE_ID,PERMISSION_ID)
);
CREATE TABLE "USER"
(
  ID Integer NOT NULL,
  COMPANY_ID Integer,
  FIRST_NAME Varchar(30),
  LAST_NAME Varchar(30),
  SALUTATION Varchar(30),
  ADDRESS Varchar(50),
  CITY Varchar(50),
  POST_CODE Varchar(10),
  COUNTRY Varchar(50),
  FIXED_PHONE Varchar(30),
  CELL_PHONE Varchar(30),
  E_MAIL Varchar(50),
  LOGIN Varchar(50) NOT NULL,
  "PASSWORD" Varchar(20),
  ENABLED Integer,
  SHOW_IN_PHONELIST Integer,
  LANGUAGE_ID Integer,
  PASSWORD_HASH Varchar(100),
  PASSWORD_SALT Varchar(100),
  CONSTRAINT USER_PK PRIMARY KEY (ID),
  UNIQUE (LOGIN)
);
CREATE TABLE USER_HAS_BUILDING_UNIT
(
  USER_ID Integer NOT NULL,
  BUILDING_UNIT_ID Integer NOT NULL,
  CONSTRAINT USER_HAS_BUILDING_UNIT_PK PRIMARY KEY (USER_ID,BUILDING_UNIT_ID)
);
CREATE TABLE USER_HAS_ROLE
(
  USER_ID Integer NOT NULL,
  ROLE_ID Integer NOT NULL,
  CONSTRAINT USER_HAS_ROLE_PK PRIMARY KEY (USER_ID,ROLE_ID)
);
/********************* VIEWS **********************/

CREATE VIEW V_ARTICLE_NOTIFICATIONS (ID, HEADER, FIRST_NAME, LAST_NAME, "COUNT")
AS  
SELECT a.ID, a.HEADER, c.FIRST_NAME, c.LAST_NAME,
(SELECT COUNT(*) FROM LOG b where a.ID = b.ARTICLE_ID and b.OPERATION_ID = 5) as "COUNT"
FROM ARTICLE a
left join "USER" c on c.ID = a.CREATED_BY_USER_ID
where a.COMPANY_ID = 1 and a.ID > 269
order by a.id desc;
CREATE VIEW V_ARTICLE_NOT_PUBLISHED (ID, COMPANY_ID, HEADER, CREATION_DATE)
AS  
SELECT a.ID, a.COMPANY_ID, a.HEADER, a.CREATION_DATE
FROM ARTICLE a
where a.PUBLISHED = 0
order by a.ID desc;
CREATE VIEW V_ARTICLE_TOP (ARTICLE_ID, HEADER, "COUNT")
AS   
SELECT 
  l.ARTICLE_ID,
  a.HEADER,
  count(*) as "COUNT"
FROM LOG l
LEFT JOIN ARTICLE a ON (a.ID = l.ARTICLE_ID)
WHERE l.OPERATION_ID = 3
GROUP BY
  l.ARTICLE_ID,
  a.HEADER
ORDER BY
  count(*) desc;
CREATE VIEW V_ARTICLE_TOP_EXCL_ROBOTS (ARTICLE_ID, HEADER, "COUNT")
AS  
SELECT 
  l.ARTICLE_ID,
  a.HEADER,
  count(*) as "COUNT"
FROM LOG l
LEFT JOIN ARTICLE a ON (a.ID = l.ARTICLE_ID)
LEFT JOIN LOG_ROBOTS r ON (r.USER_AGENT = l.USER_AGENT)
WHERE l.OPERATION_ID = 3 AND l.USER_AGENT IS NOT NULL AND r.USER_AGENT IS NULL
GROUP BY
  l.ARTICLE_ID,
  a.HEADER
ORDER BY
  count(*) desc;
CREATE VIEW V_ARTICLE_WITHOUT_ROLE (ID, COMPANY_ID, HEADER, CREATION_DATE)
AS 
SELECT 
    a.ID, 
    a.COMPANY_ID, 
    a.HEADER, 
    a.CREATION_DATE
FROM ARTICLE a
left join ARTICLE_IS_VISIBLE_TO_ROLE b on b.ARTICLE_ID = a.ID
where b.ARTICLE_ID is null
order by a.ID desc
;
CREATE VIEW V_INQUIRY_LOG (VOTING_TIME, FIRST_NAME, LAST_NAME, ANSWER, QUESTION)
AS  
SELECT 
  a.VOTING_TIME
  ,u.FIRST_NAME
  ,u.LAST_NAME
  ,b.DESCRIPTION as ANSWER
  ,c.DESCRIPTION as QUESTION
FROM INQUIRY_VOTING_LOG a
left join INQUIRY_OPTION b on b.ID = a.INQUIRY_OPTION_ID
left join INQUIRY c on c.ID = b.INQUIRY_ID
left join "USER" u on u.ID = a.USER_ID
order by a.ID desc;
CREATE VIEW V_LOG (ID, "TIME", USER_ID, COMPANY_ID, LAST_NAME, FIRST_NAME, OPERATION_ID, OPERATION, ARTICLE_ID, ARTICLE, REMOTE_IP, USER_AGENT)
AS       
SELECT 
l.ID, 
l."TIME", 
l.USER_ID, 
u.COMPANY_ID,
u.LAST_NAME, 
u.FIRST_NAME, 
l.OPERATION_ID, 
o.DESCRIPTION AS OPERATION, 
l.ARTICLE_ID, 
a.HEADER AS ARTICLE,
l.REMOTE_IP,
l.USER_AGENT
FROM LOG l
LEFT JOIN "USER" u ON (u.ID = l.USER_ID)
LEFT JOIN LOG_OPERATION o ON (o.ID = l.OPERATION_ID)
LEFT JOIN ARTICLE a ON (a.ID = l.ARTICLE_ID)
LEFT JOIN LOG_ROBOTS r ON (r.USER_AGENT = l.USER_AGENT)
WHERE r.USER_AGENT IS null
ORDER BY l.ID DESC;
CREATE VIEW V_LOG_BOT_STAT (USER_AGENT, "COUNT", LAST_TIME)
AS      
SELECT a.USER_AGENT, count(*) AS "COUNT", max(l."TIME") AS "LAST_TIME"
FROM LOG_ROBOTS a
LEFT JOIN LOG l ON (l.USER_AGENT = a.USER_AGENT)
group by a.USER_AGENT
order by count(*) desc;
CREATE VIEW V_LOG_BROWSERS (BROWSER, "COUNT")
AS 
select BROWSER, "COUNT"
from (
SELECT 'MSIE' as "BROWSER", count(*) as "COUNT" FROM LOG a where a.USER_AGENT like '%MSIE%'
UNION
SELECT 'Firefox' as "BROWSER", count(*) as "COUNT" FROM LOG a where a.USER_AGENT like '%Firefox%'
UNION
SELECT 'iPhone' as "BROWSER", count(*) as "COUNT" FROM LOG a where a.USER_AGENT like '%iPhone%'
UNION
SELECT 'iPad' as "BROWSER", count(*) as "COUNT" FROM LOG a where a.USER_AGENT like '%iPad%'
UNION
SELECT 'Android' as "BROWSER", count(*) as "COUNT" FROM LOG a where a.USER_AGENT like '%Android%'
UNION
SELECT 'Symbian' as "BROWSER", count(*) as "COUNT" FROM LOG a where a.USER_AGENT like '%Symbian%'
UNION
SELECT 'Chrome' as "BROWSER", count(*) as "COUNT" FROM LOG a where a.USER_AGENT like '%Chrome%'
UNION
SELECT 'Opera' as "BROWSER", count(*) as "COUNT" FROM LOG a where a.USER_AGENT like '%Opera%'
UNION
SELECT 'X11' as "BROWSER", count(*) as "COUNT" FROM LOG a where a.USER_AGENT like '%X11%'
)
order by "COUNT" desc
;
CREATE VIEW V_LOG_MONTH_COUNTER ("Year", "Month", "Total", "Robots", "Users")
AS     
SELECT 
    total."Year",
    total."Month",
    total."Total",
    robots."Robots",
    users."Users"
FROM 
(
SELECT 
    extract(Year from a."TIME") AS "Year",
    extract(Month from a."TIME") AS "Month",
    count(*) AS "Total"
FROM LOG a
group by 
    extract(Year from a."TIME"),
    extract(Month from a."TIME")
) total
LEFT JOIN 
(
SELECT 
    extract(Year from a."TIME") AS "Year",
    extract(Month from a."TIME") AS "Month",
    count(*) AS "Robots"
FROM LOG a
LEFT JOIN LOG_ROBOTS r ON (r.USER_AGENT = a.USER_AGENT)
WHERE r.USER_AGENT IS NOT null
group by 
    extract(Year from a."TIME"),
    extract(Month from a."TIME")
) robots ON (robots."Year" = total."Year") and (robots."Month" = total."Month")
LEFT JOIN 
(
SELECT 
    extract(Year from a."TIME") AS "Year",
    extract(Month from a."TIME") AS "Month",
    count(*) AS "Users"
FROM LOG a
LEFT JOIN LOG_ROBOTS r ON (r.USER_AGENT = a.USER_AGENT)
WHERE r.USER_AGENT IS null
group by 
    extract(Year from a."TIME"),
    extract(Month from a."TIME")
) users ON (users."Year" = total."Year") and (users."Month" = total."Month")
order by
    "Year",
    "Month"
;
CREATE VIEW V_USERS_HAS_ROLE (DESCRIPTION, LAST_NAME, FIRST_NAME)
AS   
SELECT a.DESCRIPTION, u.LAST_NAME, u.FIRST_NAME
FROM "ROLE" a
left join USER_HAS_ROLE h on (h.ROLE_ID = a.ID)
left join "USER" u on (u.ID = h.USER_ID)
where a.id in (1,2,3,5) and (u.ID is not null)
order by a.DESCRIPTION, u.LAST_NAME, u.FIRST_NAME;
CREATE VIEW V_USERS_MISSING_ROLE_ALL (ID, COMPANY_ID, FIRST_NAME, LAST_NAME, ENABLED)
AS  
SELECT a.ID, a.COMPANY_ID, a.FIRST_NAME, a.LAST_NAME, a.ENABLED
FROM "USER" a
left join USER_HAS_ROLE h on (h.USER_ID = a.ID) and (h.ROLE_ID = 6)
where a.COMPANY_ID = 1 and h.ROLE_ID is null
;
CREATE VIEW V_USERS_MISSING_ROLE_VLASTNIK (FIRST_NAME, LAST_NAME, ENABLED, LAST_LOGIN)
AS  
SELECT a.FIRST_NAME, a.LAST_NAME, a.ENABLED, c.LAST_LOGIN
FROM "USER" a
left join USER_HAS_ROLE b on b.USER_ID = a.ID and b.ROLE_ID = 4
left join 
(
SELECT a.USER_ID, max(a."TIME") as LAST_LOGIN
FROM LOG a
where a.OPERATION_ID = 1
group by
a.USER_ID
) c on c.USER_ID = a.ID
where a.COMPANY_ID = 1 and a.ENABLED = 1 and b.ROLE_ID is null;
CREATE VIEW V_USERS_UNITS (FIRST_NAME, LAST_NAME, DESCRIPTION)
AS  
SELECT 
u.FIRST_NAME,
u.LAST_NAME,
b.DESCRIPTION
FROM USER_HAS_BUILDING_UNIT a
LEFT JOIN "USER" u ON u.ID = a.USER_ID
LEFT JOIN BUILDING_UNIT b ON b.ID = a.BUILDING_UNIT_ID
ORDER BY u.LAST_NAME;
/******************* EXCEPTIONS *******************/

/******************** TRIGGERS ********************/

SET TERM ^ ;
CREATE TRIGGER TR_ARTICLE FOR ARTICLE ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN 
  if (new.id is null) then
  begin
    new.id = gen_id( GE_ARTICLE, 1 );
  end
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TR_ARTICLE_ATTACHMENT FOR ARTICLE_ATTACHMENT ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN 
  if (new.id is null) then
  begin
    new.id = gen_id( GE_ARTICLE_ATTACHMENT, 1 );
  end
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TR_ARTICLE_COMMENT FOR ARTICLE_COMMENT ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN 
  if (new.id is null) then
  begin
    new.id = gen_id( GE_ARTICLE_COMMENT, 1 );
  end
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TR_BUILDING FOR BUILDING ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN 
  if (new.id is null) then
  begin
    new.id = gen_id( GE_BUILDING, 1 );
  end
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TR_BUILDING_UNIT FOR BUILDING_UNIT ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN 
  if (new.id is null) then
  begin
    new.id = gen_id( GE_BUILDING_UNIT, 1 );
  end
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TR_COMPANY FOR COMPANY ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN 
  if (new.id is null) then
  begin
    new.id = gen_id( GE_COMPANY, 1 );
  end
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TR_INQUIRY FOR INQUIRY ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN 
    if (new.id is null) then
  begin
    new.id = gen_id( GE_INQUIRY, 1 );
  end
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TR_INQUIRY_OPTION FOR INQUIRY_OPTION ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN 
    if (new.id is null) then
  begin
    new.id = gen_id( GE_INQUIRY_OPTION, 1 );
  end
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TR_INQUIRY_VOTING_LOG FOR INQUIRY_VOTING_LOG ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN 
    if (new.id is null) then
  begin
    new.id = gen_id( GE_INQUIRY_VOTING_LOG, 1 );
  end
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TR_LOG FOR LOG ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN 
if (new.id is null) then
  begin
    new.id = gen_id( GE_LOG, 1 );
  end
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TR_LOG_ROBOTS FOR LOG_ROBOTS ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN 
  if (new.id is null) then
  begin
    new.id = gen_id( GE_LOG_ROBOTS, 1 );
  end
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TR_MENU_TREE FOR MENU_TREE ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN 
  if (new.id is null) then
  begin
    new.id = gen_id( GE_MENU_TREE, 1 );
  end
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TR_MESSAGE_QUEUE FOR MESSAGE_QUEUE ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN 
  if (new.id is null) then
  begin
    new.id = gen_id( GE_MESSAGE_QUEUE, 1 );
  end
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TR_MINI_NEWS FOR MINI_NEWS ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN 
if (new.id is null) then
  begin
    new.id = gen_id( GE_MINI_NEWS, 1 );
  end
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TR_ROLE FOR ROLE ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN 
  if (new.id is null) then
  begin
    new.id = gen_id( GE_ROLE, 1 );
  end
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER TR_USER FOR USER ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN 
  if (new.id is null) then
  begin
    new.id = gen_id( GE_USER, 1 );
  end
END^
SET TERM ; ^

SET TERM ^ ;
ALTER PROCEDURE SP_CREATE_COMPANY (
    NAME Varchar(50) )
RETURNS (
    COMPANY_ID Integer )
AS
DECLARE VARIABLE ID INT;
DECLARE VARIABLE ADMIN_ROLE_ID INT;
DECLARE VARIABLE ANONYMOUS_ROLE_ID INT;
DECLARE VARIABLE ANONYMOUS_USER_ID INT;
BEGIN
  
  /* COMPANY */
  INSERT INTO COMPANY (NAME, ADDRESS, CITY, POST_CODE, PHONE, FAX, E_MAIL, REGISTRATION_NO, VAT_REGISTRATION_NO, DATABASE_CREATION_DATE, INTERNET_DOMAIN, PICTURE_CONTENT_TYPE, PICTURE_FILENAME, PICTURE_DATA)
  VALUES (:NAME, '', '', '', '', '', '', '', '', current_timestamp, '', '', '', null) RETURNING ID INTO :COMPANY_ID;
  
  /* BUILDING */
  INSERT INTO BUILDING (COMPANY_ID, ADDRESS, CITY, POST_CODE, REGISTRATION_ID) VALUES (:COMPANY_ID, '', '', '', '');
  
  /* MENU */
  INSERT INTO MENU_TREE (COMPANY_ID, PARENT_ID, DESCRIPTION) VALUES (:COMPANY_ID, null, 'Vývìska');
  INSERT INTO MENU_TREE (COMPANY_ID, PARENT_ID, DESCRIPTION) VALUES (:COMPANY_ID, null, 'Zápisy');
  INSERT INTO MENU_TREE (COMPANY_ID, PARENT_ID, DESCRIPTION) VALUES (:COMPANY_ID, null, 'Smlouvy');
  INSERT INTO MENU_TREE (COMPANY_ID, PARENT_ID, DESCRIPTION) VALUES (:COMPANY_ID, null, 'Dokumenty');
  
  /* ROLE */
  INSERT INTO "ROLE" (COMPANY_ID, DESCRIPTION) VALUES (:COMPANY_ID, 'Administrátor') RETURNING ID INTO :ADMIN_ROLE_ID;
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ADMIN_ROLE_ID, 102);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ADMIN_ROLE_ID, 103);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ADMIN_ROLE_ID, 304);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ADMIN_ROLE_ID, 100);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ADMIN_ROLE_ID, 101);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ADMIN_ROLE_ID, 202);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ADMIN_ROLE_ID, 106);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ADMIN_ROLE_ID, 104);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ADMIN_ROLE_ID, 105);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ADMIN_ROLE_ID, 300);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ADMIN_ROLE_ID, 301);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ADMIN_ROLE_ID, 302);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ADMIN_ROLE_ID, 303);
  INSERT INTO "ROLE" (COMPANY_ID, DESCRIPTION) VALUES (:COMPANY_ID, 'Redaktor') RETURNING ID INTO :ID;
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 304);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 101);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 202);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 300);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 106);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 301);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 302);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 303);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 105);
  INSERT INTO "ROLE" (COMPANY_ID, DESCRIPTION) VALUES (:COMPANY_ID, 'Editor') RETURNING ID INTO :ID;
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 101);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 202);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 300);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 106);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 105);
  INSERT INTO "ROLE" (COMPANY_ID, DESCRIPTION) VALUES (:COMPANY_ID, 'Vlastník') RETURNING ID INTO :ID;
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 102);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 103);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 101);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 203);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 202);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 106);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 104);
  INSERT INTO "ROLE" (COMPANY_ID, DESCRIPTION) VALUES (:COMPANY_ID, 'Èlen výboru') RETURNING ID INTO :ID;
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 102);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 103);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 101);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 202);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 106);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 104);
  INSERT INTO "ROLE" (COMPANY_ID, DESCRIPTION) VALUES (:COMPANY_ID, 'Nepøihlášený uživatel') RETURNING ID INTO :ANONYMOUS_ROLE_ID;
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ANONYMOUS_ROLE_ID, 101);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ANONYMOUS_ROLE_ID, 106);
  INSERT INTO "ROLE" (COMPANY_ID, DESCRIPTION) VALUES (:COMPANY_ID, 'Externí osoba') RETURNING ID INTO :ID;
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 102);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 101);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 202);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 106);
    INSERT INTO ROLE_HAS_PERMISSION (ROLE_ID, PERMISSION_ID) VALUES (:ID, 104);
  
  /* USER */  
  INSERT INTO "USER" (COMPANY_ID, FIRST_NAME, LAST_NAME, SALUTATION, ADDRESS, CITY, POST_CODE, COUNTRY, FIXED_PHONE, CELL_PHONE, E_MAIL, LOGIN, "PASSWORD", ENABLED, SHOW_IN_PHONELIST, LANGUAGE_ID) 
    VALUES (:COMPANY_ID, 'Admin', 'Admin', '', '', '', '', '', '', '', '', 'admin', 'masterkey', 1, 0, 1) RETURNING ID INTO :ID;
    INSERT INTO USER_HAS_ROLE (USER_ID, ROLE_ID) VALUES (:ID, :ADMIN_ROLE_ID);
    
  INSERT INTO "USER" (COMPANY_ID, FIRST_NAME, LAST_NAME, SALUTATION, ADDRESS, CITY, POST_CODE, COUNTRY, FIXED_PHONE, CELL_PHONE, E_MAIL, LOGIN, "PASSWORD", ENABLED, SHOW_IN_PHONELIST, LANGUAGE_ID) 
    VALUES (:COMPANY_ID, 'Anonymní', 'Uživatel', '', '', '', '', '', '', '', '', 'anonymous', '', 0, 0, 1) RETURNING ID INTO :ANONYMOUS_USER_ID;
    INSERT INTO USER_HAS_ROLE (USER_ID, ROLE_ID) VALUES (:ANONYMOUS_USER_ID, :ANONYMOUS_ROLE_ID);
  
  /* APPLICATION SETUP */
  INSERT INTO APPLICATION_SETUP (ID, COMPANY_ID, "VALUE") VALUES ('anonymous.user.id', :COMPANY_ID, :ANONYMOUS_USER_ID);
  INSERT INTO APPLICATION_SETUP (ID, COMPANY_ID, "VALUE") VALUES ('article.menu.default.item', :COMPANY_ID, '0');
  INSERT INTO APPLICATION_SETUP (ID, COMPANY_ID, "VALUE") VALUES ('article.page.size', :COMPANY_ID, '10');
  INSERT INTO APPLICATION_SETUP (ID, COMPANY_ID, "VALUE") VALUES ('article.top.size', :COMPANY_ID, '5');
  INSERT INTO APPLICATION_SETUP (ID, COMPANY_ID, "VALUE") VALUES ('error.report.recipient', :COMPANY_ID, 'jaroslav.beran@gmail.com');
  --INSERT INTO APPLICATION_SETUP (ID, COMPANY_ID, "VALUE") VALUES ('google.analytics.id', :COMPANY_ID, '');
  INSERT INTO APPLICATION_SETUP (ID, COMPANY_ID, "VALUE") VALUES ('http.meta.description', :COMPANY_ID, 'stránky Spoleèenství vlastníkù');
  INSERT INTO APPLICATION_SETUP (ID, COMPANY_ID, "VALUE") VALUES ('http.meta.keywords', :COMPANY_ID, 'svj, spoleèenství');
  INSERT INTO APPLICATION_SETUP (ID, COMPANY_ID, "VALUE") VALUES ('mail.login', :COMPANY_ID, '');
  INSERT INTO APPLICATION_SETUP (ID, COMPANY_ID, "VALUE") VALUES ('mail.password', :COMPANY_ID, '');
  INSERT INTO APPLICATION_SETUP (ID, COMPANY_ID, "VALUE") VALUES ('mail.sender', :COMPANY_ID, '');
  INSERT INTO APPLICATION_SETUP (ID, COMPANY_ID, "VALUE") VALUES ('mail.smtp', :COMPANY_ID, '');
  INSERT INTO APPLICATION_SETUP (ID, COMPANY_ID, "VALUE") VALUES ('mail.template.article.notification', :COMPANY_ID, 'Dobrý den,<br><br>rádi bychom Vás upozornili na následující èlánek na stránkách SVJ. <br><br>%s<br><br>S pozdravem,<br>Výbor SVJ');
  INSERT INTO APPLICATION_SETUP (ID, COMPANY_ID, "VALUE") VALUES ('mail.template.lost.password', :COMPANY_ID, '<html><body>Dobrý den,<br>Vaše pøihlašovací údaje jsou:<br><br>%s<br><br>Web SVJ</body></html>');
 
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE SP_DROP_COMPANY (
    ID Integer )
AS
BEGIN

  /* EMPTY LOG */
  DELETE FROM LOG a WHERE a.USER_ID in (SELECT u.ID FROM "USER" u WHERE u.COMPANY_ID = :ID);

  /* USER HAS */
  DELETE FROM USER_HAS_BUILDING_UNIT a WHERE a.USER_ID in (SELECT u.ID FROM "USER" u WHERE u.COMPANY_ID = :ID);
  DELETE FROM USER_HAS_ROLE a WHERE a.USER_ID in (SELECT u.ID FROM "USER" u WHERE u.COMPANY_ID = :ID);  
  
  /* ARTICLE */
  DELETE FROM ARTICLE_ATTACHMENT a WHERE a.ARTICLE_ID in (SELECT u.ID FROM ARTICLE u WHERE u.COMPANY_ID = :ID);
  DELETE FROM ARTICLE_COMMENT a WHERE a.ARTICLE_ID in (SELECT u.ID FROM ARTICLE u WHERE u.COMPANY_ID = :ID);
  DELETE FROM ARTICLE_IS_VISIBLE_TO_ROLE a WHERE a.ARTICLE_ID in (SELECT u.ID FROM ARTICLE u WHERE u.COMPANY_ID = :ID);
  DELETE FROM ARTICLE a WHERE a.COMPANY_ID = :ID;
  
  /* NEWS */
  DELETE FROM MINI_NEWS a WHERE a.COMPANY_ID  = :ID;
  
  /* BUILDING */
  DELETE FROM BUILDING_UNIT a WHERE a.BUILDING_ID in (SELECT u.ID FROM BUILDING u WHERE u.COMPANY_ID = :ID);
  DELETE FROM BUILDING a WHERE a.COMPANY_ID = :ID;
  
  /* INQUIRY */
  DELETE FROM INQUIRY_VOTING_LOG a WHERE a.USER_ID in (SELECT u.ID FROM "USER" u WHERE u.COMPANY_ID = :ID);
  DELETE FROM INQUIRY_OPTION a WHERE a.INQUIRY_ID in (SELECT u.ID FROM INQUIRY u WHERE u.COMPANY_ID = :ID);
  DELETE FROM INQUIRY a WHERE a.COMPANY_ID = :ID;
  
  /* ROLE */
  DELETE FROM ROLE_HAS_PERMISSION a WHERE a.ROLE_ID in (SELECT u.ID FROM "ROLE" u WHERE u.COMPANY_ID = :ID);
  DELETE FROM "ROLE" a WHERE a.COMPANY_ID  = :ID;
  
  /* USER */
  DELETE FROM "USER" a WHERE a.COMPANY_ID  = :ID;
  
  /* COMPANY */
  DELETE FROM MENU_TREE a WHERE a.COMPANY_ID  = :ID;
  DELETE FROM MESSAGE_QUEUE a WHERE a.COMPANY_ID  = :ID;
  DELETE FROM APPLICATION_SETUP a WHERE a.COMPANY_ID  = :ID;
  DELETE FROM COMPANY a WHERE a.ID  = :ID;
 
END^
SET TERM ; ^


SET TERM ^ ;
ALTER PROCEDURE SP_DROP_USER (
    USER_ID Integer )
AS
BEGIN

    DELETE FROM USER_HAS_BUILDING_UNIT a WHERE a.USER_ID = :USER_ID;
    DELETE FROM USER_HAS_ROLE a WHERE a.USER_ID = :USER_ID;
    DELETE FROM LOG a WHERE a.USER_ID = :USER_ID;
    DELETE FROM "USER" a WHERE a.ID = :USER_ID;
 
END^
SET TERM ; ^


ALTER TABLE APPLICATION_SETUP ADD
  FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID);
ALTER TABLE ARTICLE ADD
  FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID);
ALTER TABLE ARTICLE ADD
  FOREIGN KEY (MENU_NODE_ID) REFERENCES MENU_TREE (ID);
ALTER TABLE ARTICLE ADD
  FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (ID);
ALTER TABLE ARTICLE ADD
  FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES "USER" (ID);
CREATE DESCENDING INDEX IDX_ARTICLE1 ON ARTICLE (CREATION_DATE);
ALTER TABLE ARTICLE_ATTACHMENT ADD
  FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ID);
ALTER TABLE ARTICLE_ATTACHMENT ADD
  FOREIGN KEY (USER_ID) REFERENCES "USER" (ID);
ALTER TABLE ARTICLE_COMMENT ADD
  FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ID);
ALTER TABLE ARTICLE_COMMENT ADD
  FOREIGN KEY (USER_ID) REFERENCES "USER" (ID);
ALTER TABLE ARTICLE_INQUIRY ADD
  FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ID);
ALTER TABLE ARTICLE_INQUIRY_OPTION ADD
  FOREIGN KEY (INQUIRY_ID) REFERENCES ARTICLE_INQUIRY (ID);
ALTER TABLE ARTICLE_INQUIRY_VOTING_LOG ADD
  FOREIGN KEY (INQUIRY_OPTION_ID) REFERENCES ARTICLE_INQUIRY_OPTION (ID);
ALTER TABLE ARTICLE_INQUIRY_VOTING_LOG ADD
  FOREIGN KEY (USER_ID) REFERENCES "USER" (ID);
ALTER TABLE ARTICLE_IS_VISIBLE_TO_ROLE ADD
  FOREIGN KEY (ROLE_ID) REFERENCES "ROLE" (ID);
ALTER TABLE ARTICLE_IS_VISIBLE_TO_ROLE ADD
  FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ID);
ALTER TABLE BUILDING ADD
  FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID);
ALTER TABLE BUILDING_UNIT ADD
  FOREIGN KEY (BUILDING_ID) REFERENCES BUILDING (ID);
ALTER TABLE BUILDING_UNIT ADD
  FOREIGN KEY (BUILDING_UNIT_TYPE_ID) REFERENCES BUILDING_UNIT_TYPE (ID);
ALTER TABLE INQUIRY ADD
  FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID);
ALTER TABLE INQUIRY ADD
  FOREIGN KEY (USER_ID) REFERENCES "USER" (ID);
ALTER TABLE INQUIRY_OPTION ADD
  FOREIGN KEY (INQUIRY_ID) REFERENCES INQUIRY (ID);
ALTER TABLE INQUIRY_VOTING_LOG ADD
  FOREIGN KEY (INQUIRY_OPTION_ID) REFERENCES INQUIRY_OPTION (ID);
ALTER TABLE INQUIRY_VOTING_LOG ADD
  FOREIGN KEY (USER_ID) REFERENCES "USER" (ID);
ALTER TABLE LANGUAGE_DICTIONARY ADD
  FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (ID);
ALTER TABLE LOG ADD
  FOREIGN KEY (USER_ID) REFERENCES "USER" (ID);
ALTER TABLE LOG ADD
  FOREIGN KEY (OPERATION_ID) REFERENCES LOG_OPERATION (ID);
ALTER TABLE LOG ADD
  FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ID);
CREATE INDEX IDX_LOG1 ON LOG (ARTICLE_ID,OPERATION_ID);
ALTER TABLE MENU_TREE ADD
  FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID);
ALTER TABLE MENU_TREE ADD
  FOREIGN KEY (PARENT_ID) REFERENCES MENU_TREE (ID);
ALTER TABLE MESSAGE_QUEUE ADD
  FOREIGN KEY (MESSAGE_TYPE_ID) REFERENCES MESSAGE_TYPE (ID);
ALTER TABLE MESSAGE_QUEUE ADD
  FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID);
ALTER TABLE MINI_NEWS ADD
  FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID);
ALTER TABLE MINI_NEWS ADD
  FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (ID);
ALTER TABLE MINI_NEWS ADD
  FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES "USER" (ID);
ALTER TABLE "ROLE" ADD
  FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID);
ALTER TABLE ROLE_HAS_PERMISSION ADD
  FOREIGN KEY (ROLE_ID) REFERENCES "ROLE" (ID);
ALTER TABLE ROLE_HAS_PERMISSION ADD
  FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSION (ID);
ALTER TABLE "USER" ADD
  FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID);
ALTER TABLE "USER" ADD
  FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGE (ID);
ALTER TABLE USER_HAS_BUILDING_UNIT ADD
  FOREIGN KEY (USER_ID) REFERENCES "USER" (ID);
ALTER TABLE USER_HAS_BUILDING_UNIT ADD
  FOREIGN KEY (BUILDING_UNIT_ID) REFERENCES BUILDING_UNIT (ID);
ALTER TABLE USER_HAS_ROLE ADD
  FOREIGN KEY (USER_ID) REFERENCES "USER" (ID);
ALTER TABLE USER_HAS_ROLE ADD
  FOREIGN KEY (ROLE_ID) REFERENCES "ROLE" (ID);
GRANT R_WEB TO WEB;
GRANT EXECUTE
 ON PROCEDURE SP_CREATE_COMPANY TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE SP_DROP_COMPANY TO  SYSDBA;

GRANT EXECUTE
 ON PROCEDURE SP_DROP_USER TO  SYSDBA;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON APPLICATION_SETUP TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON APPLICATION_SETUP TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ARTICLE TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ARTICLE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ARTICLE_ATTACHMENT TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ARTICLE_ATTACHMENT TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ARTICLE_COMMENT TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ARTICLE_COMMENT TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ARTICLE_INQUIRY TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ARTICLE_INQUIRY TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ARTICLE_INQUIRY_OPTION TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ARTICLE_INQUIRY_OPTION TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ARTICLE_INQUIRY_VOTING_LOG TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ARTICLE_INQUIRY_VOTING_LOG TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ARTICLE_IS_VISIBLE_TO_ROLE TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ARTICLE_IS_VISIBLE_TO_ROLE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON BUILDING TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON BUILDING TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON BUILDING_UNIT TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON BUILDING_UNIT TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON BUILDING_UNIT_TYPE TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON BUILDING_UNIT_TYPE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON COMPANY TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON COMPANY TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON INQUIRY TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON INQUIRY TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON INQUIRY_OPTION TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON INQUIRY_OPTION TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON INQUIRY_VOTING_LOG TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON INQUIRY_VOTING_LOG TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON LANGUAGE TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON LANGUAGE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON LANGUAGE_DICTIONARY TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON LANGUAGE_DICTIONARY TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON LOG TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON LOG TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON LOG_OPERATION TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON LOG_OPERATION TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON LOG_ROBOTS TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON LOG_ROBOTS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON MENU_TREE TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON MENU_TREE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON MESSAGE_QUEUE TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON MESSAGE_QUEUE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON MESSAGE_TYPE TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON MESSAGE_TYPE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON MINI_NEWS TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON MINI_NEWS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON PERMISSION TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON PERMISSION TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON "ROLE" TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON "ROLE" TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ROLE_HAS_PERMISSION TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON ROLE_HAS_PERMISSION TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON "USER" TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON "USER" TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON USER_HAS_BUILDING_UNIT TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON USER_HAS_BUILDING_UNIT TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON USER_HAS_ROLE TO ROLE R_WEB;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON USER_HAS_ROLE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON V_ARTICLE_NOTIFICATIONS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON V_ARTICLE_NOT_PUBLISHED TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON V_ARTICLE_TOP TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON V_ARTICLE_TOP_EXCL_ROBOTS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON V_ARTICLE_WITHOUT_ROLE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON V_INQUIRY_LOG TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON V_LOG TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON V_LOG_BOT_STAT TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON V_LOG_BROWSERS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON V_LOG_MONTH_COUNTER TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON V_USERS_HAS_ROLE TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON V_USERS_MISSING_ROLE_ALL TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON V_USERS_MISSING_ROLE_VLASTNIK TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON V_USERS_UNITS TO  SYSDBA WITH GRANT OPTION;

